### PR TITLE
Explicitly call str in partial_by_order

### LINKED ISSUE #912: BUG: dask.array errors on timedelta64 arithmetic
```
da.from_array(np.array([np.timedelta64(10, 'h')]), chunks=(1,)) / np.timedelta64(1, 'h')
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-38c05cd03730> in <module>()
----> 1 da.from_array(np.array([np.timedelta64(10, 'h')]), chunks=(1,)) / np.timedelta64(1, 'h')

/export/data/dask/dask/array/core.pyc in __div__(self, other)
   1044         return elemwise(operator.and_, other, self)
   1045     def __div__(self, other):
-> 1046         return elemwise(operator.div, self, other)
   1047     def __rdiv__(self, other):
   1048         return elemwise(operator.div, other, self)

/export/data/dask/dask/array/core.pyc in elemwise(op, *args, **kwargs)
   2085 
   2086     if other:
-> 2087         op2 = partial_by_order(op, other)
   2088     else:
   2089         op2 = op

/export/data/dask/dask/array/core.pyc in partial_by_order(op, other)
   1979     else:
   1980         other_arg = '...'
-> 1981     f.__name__ = '{0}({1})'.format(op.__name__, other_arg)
   1982     return f
   1983 

TypeError: don't know how to convert scalar number to long
```

### PR DESCRIPTION
**Pull request by jcrist**
Fixes #912

### CODE REVIEW

**Comment by jcrist** [comment]
Failures are due to bokeh incompatibilities with recent release. Ping @shoyer for review.

**Comment by shoyer** [comment]
Bokeh? :)

**Comment by jcrist** [comment]
I meant test failures weren't related to this fix. This bug was just a repr issue :).

**Comment by shoyer** [comment]
Oh, gotcha. This looks good to me.

**Comment by shoyer** [comment]
Thanks for the quick fix!

**Pull request merged**
