### PR TITLE
Remove hack in _loc

### PR DESCRIPTION
**Pull request by jcrist**

### CODE REVIEW

**Comment by cpcloud** [comment]
+1000

**Comment by mrocklin** [comment]
What was the history here?

**Comment by cpcloud** [comment]
If there were no values between two times, that would be an empty series. With resampling, no values between two times should produce `nan` at a values at those times, evenly sampled by the resampling period.

**Comment by mrocklin** [comment]
Why was it needed before and isn't needed now?

**Comment by jcrist** [comment]
Shoot, we don't cover that case, and we're not testing for it. Still need to fix that, don't merge.

**Comment by cpcloud** [comment]
Hm, okay I thought there was a test for this

**Comment by jcrist** [comment]
There's a few, but as long as there's some datapoints in a partition, everything's fine. If the partition is empty though, then this fails. Chance of that happening = low, but it happens.

**Comment by cpcloud** [comment]
Could `repartition` do this?

**Comment by cpcloud** [comment]
Or another function that repartitioned and filled in empty slices with `nan`?

**Comment by jcrist** [comment]
It definitely shouldn't be `_loc`. I think I can fix it in `block_func` for resample.

**Comment by jcrist** [comment]
So, here's the current state of things:
- `resample` currently doesn't properly handle empty partitions (pandas fills with `NaN`, we just miss that partition)
- The `_loc` hack that is in master doesn't fix that, but it breaks some other things.
- Getting the missing partitions is nontrivial because of non-constant defaults for binning between Week and day/hour/minute/etc.... Day/hour/minute default to labeled as left of the bin, right exclusive and left inclusive (`[1, 2, 3)`). Week+ defaults to labeled as right of the bin, left exclusive, right inclusive (`(1, 2, 3]`). This makes duplicating this behavior in dask in a rigorous way hard, because the behavior is non-intuitive, and non-constant. This will require more work.

I'd like to merge this for now, as it fixes issues that break in master. A second PR will follow up fixing the few cases where we don't mirror pandas resample behavior. Thoughts?

**Pull request merged**
