### PR TITLE
Visualize now works with dask dicts

### PR DESCRIPTION
**Pull request by jcrist**
Came out of discussion in #855 with @ajfriend.

### CODE REVIEW

**Comment by mrocklin** [comment]
Not sure what's going on with the intermittent error.  Only seems to happen in python 2.7 so far.

**Comment by jcrist** [comment]
Yeah. It gives no traceback either, which is super weird. Seems to kill the build when it happens. I just restarted it, but should probably figure that out.

**Comment by mrocklin** [comment]
I've run tests in py27 several times using bash for loops.  Each failure has so far occurred in a different `dask.dataframe` test and has not been recoverable (even ctrl-c doesn't break it).  I tried tests in an environment with `pandas=1.17.0` and everything runs fine.  I suspect a recent thread-safety break in pandas.

**Comment by jcrist** [comment]
Merging soon if no comment. The failures are related to other things.

**Pull request merged**
