### PR TITLE
Close memmap'd file when finished. Close #748

### LINKED ISSUE #748: Windows error in test_array_core.py::test_memmap
An error trying to close a file while another process has access to it.
```python
_________________________________ test_memmap _________________________________

    def test_memmap():
        with tmpfile('npy') as fn_1:
            with tmpfile('npy') as fn_2:
                x = da.arange(100, chunks=15)
                target = np.memmap(fn_1, shape=x.shape, mode='w+', dtype=x.dtype)

                x.store(target)

                assert eq(target, x)

                np.save(fn_2, target)

>               assert eq(np.load(fn_2, mmap_mode='r'), x)

tests\test_array_core.py:1439:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\..\..\..\anaconda\envs\dask\lib\contextlib.py:24: in __exit__
    self.gen.next()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

extension = '.npy', dir = None

    @contextmanager
    def tmpfile(extension='', dir=None):
        extension = '.' + extension.lstrip('.')
        handle, filename = tempfile.mkstemp(extension, dir=dir)
        os.close(handle)
        os.remove(filename)

        try:
            yield filename
        finally:
            if os.path.exists(filename):
                if os.path.isdir(filename):
                    shutil.rmtree(filename)
                else:
>                   os.remove(filename)
E                   WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\us
ers\\ieuser\\appdata\\local\\temp\\tmpymijv3.npy'
```

### PR DESCRIPTION
**Pull request by cowlicks**
Fixes a bug in windows.

closes #748

### CODE REVIEW

**Comment by shoyer** [comment]
Maybe a good idea to setup Windows testing via Appveyor? This was pretty easy to do for xray.

**Comment by cowlicks** [comment]
@shoyer this was happening at some point. cc @jcrist

**Comment by jcrist** [comment]
This was done, but not merged due to slowness issues. See here: https://github.com/blaze/dask/pull/383

**Comment by jcrist** [comment]
Looks good to me.

**Pull request merged**
