### PR TITLE
Use lock in dd.read_hdf

### LINKED ISSUE #760: segmentation fault with dask.dataframe.read_hdf
I continue in my quest to use dask with a large hdf file.

After learning that my original pytables-generated HDF files might not be able to be read by dask.dataframe (because dask uses subselection: pydata/pandas#11188), I tried re-generating the files using the pandas HDFStore interface. (First I had to updated pytables overcome a different bug: pydata/pandas#10672.) (Also, in the meantime, a workaround was found for reading the pytables file into dask: #747, #759.)

Anyway, now I have a pandas-generated HDF file. I can read it with pandas, but with dask I am getting a segfault.

```python
import pandas as pd
import dask.dataframe as dd
fname = '/data/scratch/rpa/global_lagrangian/run/pandas_floats.h5'
key = '/floats/trajectories'
df = pd.read_hdf(fname, key)
ddf = dd.read_hdf(fname, key)
print(len(df))
print(len(ddf))
```

The first print statement gives ``753664023``. The second generates a segfault via the ``len`` call.

I can still call ``ddf.head()`` and ``ddf.tail()``, but other more complex operations (e.g. ``groupby``) fail, presumably due to the same underlying issue.

I am using all the latest masters of dask, pandas, and pytables.

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes #760

Suggestions welcome on how to test this.

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @rabernat @shoyer

**Comment by rabernat** [comment]
This is my minimal broken example:

```python
import pandas as pd
import dask.dataframe as dd
import numpy as np

fname = 'testfile.h5'
key = '/group/dataset'

dtype = np.dtype([('idx','i4'),('val_a','f8'),('val_b','f8')])
N = 10000000
#store = pd.HDFStore(output_fname, mode='w')
with pd.HDFStore(fname, mode='w') as store:
    recarray = np.empty(N, dtype)
    df = pd.DataFrame.from_records(recarray)
    store.append(key, df)

df = pd.read_hdf(fname, key)
ddf = dd.read_hdf(fname, key)
print(len(df))
print(len(ddf))
```

The last line gives me a segfault.

If I make N smaller, then it works. It is also platform dependent in a way I have not fully figured out.

**Comment by mrocklin** [comment]
This example unfortunately works for me both with and without these changes.

**Comment by rabernat** [comment]
It works for me on my mac laptop but breaks on my linux workstation.

Also (somewhat obviously in retrospect), ``N`` just needs to be smaller than ``chunksize`` to trigger the segfault.

I will try checking out your branch.

**Comment by TomAugspurger** [comment]
@rabernat's example failed for me on master, worked with this PR.

```python
In [2]: tables.__version__
Out[2]: '3.2.2'

In [3]: pd.__version__
Out[3]: '0.17.0rc1+63.gf5106d8'
```

HDF5 version 1.8.15 (on a mac).

**Comment by rabernat** [comment]
Yup, I can confirm that this PR fixes the issues.

**Comment by mrocklin** [comment]
Can anyone think of a nice test to ago along with this that isn't huge?  Otherwise I'm likely to merge without a test.

**Comment by TomAugspurger** [comment]
@mrocklin seems like it's the ratio of `len(df)` : `chunksize`

> Also (somewhat obviously in retrospect), N just needs to be smaller than chunksize to trigger the segfault.

```python
import pandas as pd
import dask.dataframe as dd
import numpy as np

fname = 'testfile.h5'
key = '/group/dataset'

N = 100
#store = pd.HDFStore(output_fname, mode='w')
with pd.HDFStore(fname, mode='w') as store:
    df = pd.DataFrame(np.random.randn(N, 3))
    store.append(key, df)

df = pd.read_hdf(fname, key)
ddf = dd.read_hdf(fname, key, chunksize=2)
print(len(df))
print(len(ddf))
```

segfaults reliably for me.

**Comment by mrocklin** [comment]
added as a test

**Pull request merged**
