### PR TITLE
Fix bcolz column order

### LINKED ISSUE #787: dataframe column names getting scrambled
I am loading from data from bcolz into a dask dataframe. After applying a ``.where()`` operation, the column names get scrambled.

Unfortunately I haven't been able to reproduce this with a simpler example. But here it is. Quite stuck and frustrated. (Dask version 0.7.3.)

```python
from dask import dataframe as dd
bdf = dd.from_bcolz(fname)
bdf.loc[0].compute()
```
gives
```
npart    3073441.000000
time           0.000000
vort           0.000001
x            225.023438
y            -19.984375
Name: 0, dtype: float32
```
but if I do
```
bdf.where(bdf.time==0).loc[0].compute()
```
I get
```
npart    3073441.000000
time           0.000000
x              0.000001
y            225.023438
vort         -19.984375
Name: 0, dtype: float32
```

The ``x`` and ``vort`` columns have been exchanged.

Any idea what is wrong and how to fix it?

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes #787

### CODE REVIEW

**Comment by mrocklin** [comment]
@rabernat

```python
In [1]: import dask.dataframe as dd

In [2]: df = dd.from_bcolz('test_data.bcolz')

In [3]: df.loc[0].compute()
Out[3]: 
npart   -3.531928e-36
time     0.000000e+00
x        5.859039e-40
y        2.062846e-38
vort     2.895781e+35
Name: 0, dtype: float32

In [4]: df.where(df.time==0).loc[0].compute()
Out[4]: 
npart   -3.531928e-36
time     0.000000e+00
x        5.859039e-40
y        2.062846e-38
vort     2.895781e+35
Name: 0, dtype: float32

In [5]: df.loc[0].compute()
Out[5]: 
npart   -3.531928e-36
time     0.000000e+00
x        5.859039e-40
y        2.062846e-38
vort     2.895781e+35
Name: 0, dtype: float32
```

**Comment by rabernat** [comment]
:+1: cool!

**Comment by rabernat** [comment]
Only now do I notice that there is an endianness problem with this data. But that is unrelated to this issue.

**Comment by mrocklin** [comment]
This is in.  I hope to release a new version in the next few days.

**Pull request merged**
