### PR TITLE
Refactor Array operators

### PR DESCRIPTION
**Pull request by sinhrks**
Follow-up of #616. Clea up Array operator definitions.

### CODE REVIEW

**Comment by mrocklin** [comment]
Ha, it's 6:50 in the morning in Japan.  Do you ever sleep?  :-)

**Comment by mrocklin** [comment]
@shoyer what are your thoughts on this kind of refactor?  This increases complexity but decreases boilerplate.

**Comment by shoyer** [comment]
+0 from me. I don't care strongly either way.

**Comment by sinhrks** [comment]
It is intended to meet styles applied in #616. I'm willing to fix DataFrame/Scalar side if current Array style is preferable.

**Comment by mrocklin** [comment]
I think that I slightly prefer having explicit methods in dask.array.  While I generally try to avoid boilerplate / repetitive code I think I prefer it in this case for the following reasons:

1.  It's easier for a curious newcomer to trace back how arithmetic operations work.   It's hard to discover where `__add__` is defined with the changes in this branch.
2.  Some of the normal reasons to avoid repetitive code don't apply here.  We don't expect to have to extend or alter this code much in the future.  The set of operators in Python changes slowly.

That being said, I don't see a reason to change back the dask.dataframe code.  I would wait until something forces a change before working on either of these.  I suggest that we keep this branch around in case we do end up needed to change array operators, in which case merging this will probably make those changes easier.

**Comment by mrocklin** [comment]
Closing this for now.

**Pull request closed without merging**
