### PR TITLE
WIP: Debian package

### LINKED ISSUE #412: Make Debian package
We should consider making a dask debian package.  This provides two things

1.  It allays concerns about depending on dask by projects with conservative views on packaging
2.  It assists distributed system administrators who want to install dask, either in a parallel computing or institutional/university environment.  Apparently in these contexts even `pip install` is non-trivial.

### PR DESCRIPTION
**Pull request by cowlicks**
This adds a directory `debian/` with files for building .deb packages.

To get dask included in the Debian repositories an "ITP" must be filed, and the package must be "sponsored" by an accepted debian developer. More information on this [here](https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html#adding-packages-to-debian).

Todo:

- [ ] bundle partd, locket, and toolz
- [ ] add depends for python-numpy, python-pandas, python-dill, python-zmq

python-dill is not currently in debian 8/stable/jessie, but it is in unstable and testing. This is okay since python-dask would be introduced in the unstable and testing distributions first.

This will partially close #412

### CODE REVIEW

**Comment by mrocklin** [comment]
Do we know a potential sponsor?

**Comment by cowlicks** [comment]
@mrocklin maybe we could solicit one on the blaze mailing list, or ask around continuum. I would like to have the package finished before I go asking around.

**Comment by cowlicks** [comment]
@mrocklin The standard way is to ask on the debian-mentors list. We should probably do that first.

**Comment by cowlicks** [comment]
The partd, toolz, and locket dependencies can be included in a few ways:

* making debian packages for them, and including them in debian. They are straightforward to make but this could potentially incur a lot of extra maintenance. And they might not get excepted into debian because they are new and have few users.

* including them in python-dask.py. Debian maintainers probably won't like this idea. There are several ways to do this. 
    * make dask/debian/rules smart enough to do this automatically. This has hard. Right now I download the packages from pypi. Automatically make .debs from them. And now I am trying to combine their `DEBIAN/` and `usr/` directories with the one dask generates. I'm having a hard time scripting this. right now I use rsync to combine the `usr/` directories. Combining the files in `DEBIAN/` is proving to be more difficult.
   * instead of doing this automatically I could manually add partd, locket, and toolz as subpackages to dask. Then build a .deb package. This seems easier so I'll try it tomorrow.

**Comment by cowlicks** [comment]
More issues: pandas in debian unstable is version 0.14.1 some parts of dask are broken with this version. Should we fix these?

**Comment by mrocklin** [comment]
I suggest that we table this for now.

**Comment by mrocklin** [comment]
Closing this for now.

**Pull request closed without merging**
