### PR TITLE
Add DataFrame.merge and DataFrame.join

### PR DESCRIPTION
**Pull request by sinhrks**
Add following methods which exists in ``pandas``. 

- ``DataFrame.merge``: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html
- ``DataFrame.join``: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.join.html

Also, fixed a bug ``dd.merge`` when column name is specified like ``left_on='x'`` and ``right_index=True``.

```
A = pd.DataFrame({'x': [1, 2, 3, 4, 5, 6], 'y': [1, 1, 2, 2, 3, 4]})
a = dd.repartition(A, [0, 4, 5])

B = pd.DataFrame({'y': [1, 3, 4, 4, 5, 6], 'z': [6, 5, 4, 3, 2, 1]})
b = dd.repartition(B, [0, 2, 5])

dd.merge(a, b, left_on='x', right_index=True).compute()
# stalls...
```

dd.merge(a, b, left_on='x', right_index=True).compute()

### ToDo:

Currently, ``DataFrame.join`` using ``on`` kw doesn't work as expected. I'm digging in further.

### CODE REVIEW

**Comment by sinhrks** [comment]
Strangely, some tests locally passed but failed on travis... Needs more time.

**Comment by sinhrks** [comment]
Found some failures are caused by the following issue. Trying to include it in pandas 0.17.

https://github.com/pydata/pandas/pull/10826

**Comment by mrocklin** [comment]
This looks good to me.  @sinhrks is this still WIP?

**Comment by sinhrks** [comment]
@mrocklin Yes it's ready. I'll revisit commented out tests once pandas 0.17 has been released.

**Pull request merged**
