### PR TITLE
(WIP) Fix dataframe.io API docs

### PR DESCRIPTION
**Pull request by sinhrks**
Added some functions to the list. 

One problem is all kwds in ``pd.read_csv`` are listed as "not supported" because ``dd.read_csv`` uses ``kwargs`` to handle them at once. I think there are some unsupported kwds like ``skiprows`` and ``skipfooter`` at a glance. 

Considering a easy way to apply it to the doc.

### CODE REVIEW

**Comment by mrocklin** [comment]
We could also stop using `**kwargs` and explicitly write out all of the keyword names explicitly.  This would make some of the code a bit more verbose but would make us more explicit about what keywords we do and do not support.

**Comment by mrocklin** [comment]
What is the status on this?

**Comment by sinhrks** [comment]
I agree we should use all defined keywords explicitly. I'm going to distinguish non-supported kwds, hopefully finish this weekend.

**Comment by sinhrks** [comment]
Worked on this, and found this needs some logic change and tests because now all kwds are passed as default value. Pls give me a while.

**Comment by mrocklin** [comment]
This seems to be stale.  Closing for now.  Please reopen if this starts up again.

**Pull request closed without merging**
