### PR TITLE
Ensure random seeds are different.

### LINKED ISSUE #719: random states may have same seed
The current implementation of seeding the random number generator is:

```
seeds = [self._numpy_state.randint(np.iinfo(np.int32).max) for i in sizes]
```

This can result in repetition of seeds => random sequences are the same, which is probably not what users intend. The reasoning is the same as the [birthday problem](https://en.wikipedia.org/wiki/Birthday_problem) in probability.

```
from __future__ import division

import numpy as np
from scipy.misc import comb, factorial


def prob_same(k, n=np.iinfo(np.int32).max):
    '''
    Compute the probability that at least two seeds are the same
    '''
    different = comb(n, k, exact=True) * factorial(k, exact=True)
    total = n ** k
    prob_all_different = different / total
    return 1 - prob_all_different
```

Here's a few figures:
```
In [246]: prob_same(1000)
Out[246]: 0.00023257080042193845

In [247]: prob_same(10000)
Out[247]: 0.023011865852016755

In [248]: prob_same(50000)
Out[248]: 0.4412591367423576
```

So if there are 50000 chunks, there's a 44% chance that a seed will be repeated. Probably no big deal for most use cases, but it would be better to not have to make this assumption.

It's possible to eliminate this by just sampling with replacement. Ie. change the implementation to something like:
```
seeds = self._numpy_state.choice(np.iinfo(np.int32).max, size=len(sizes), replace=True)
```

I don't know if this alternative implementation would be totally valid, since it seems like more may be required. See this [paper by L'Ecuyer](http://www.iro.umontreal.ca/~lecuyer/myftp/papers/wsc15rng.pdf). But it would effectively guarantee different seeds.

### PR DESCRIPTION
**Pull request by clarkfitzg**
Close #719.

### CODE REVIEW

**Comment by clarkfitzg** [comment]
Should I be updating something in a changelog?

**Comment by mrocklin** [comment]
Sorry for the delay in responding to this.  This looks great to me.  It looks like you're running into two issues

1.  Failing test in svd_compressed.  This was unfortunately sensitive to how we produce random seeds (and a bit of a wonky test to begin with.)  I've cleaned this up in this commit if you'd like to cherry-pick https://github.com/mrocklin/dask/commit/a15030c81bef06768c7c8f45b1a16a392cbedaf5
2.  A failing doctest that was also sensitive to how we produced random seeds.  This should probably just be changed to the new values. (see travis.ci exception in python 2.7)

**Comment by mrocklin** [comment]
We don't currently maintain a changelog.  I'd be happy to start this up if there is interest though.

**Comment by clarkfitzg** [comment]
Thanks for the pointers. I feel like Github manages changelog info well enough.

What do you think about adding a little more documentation to `dataframe.DataFrame.random_split` and `dataframe.DataFrame.random_sample` while I'm at it here?

**Comment by mrocklin** [comment]
Adding more documentation sounds delightful :)

**Comment by clarkfitzg** [comment]
Would also be nice to change it so `dataframe.DataFrame.random_split` and `dataframe.DataFrame.sample` have the same name for the `random_state` parameter, which would also match pandas. This would be a breaking change for users who use keyword args though.

**Comment by mrocklin** [comment]
Dask.dataframe is young enough and there have been enough "use at your own risk" warnings that I'm personally comfortable with a breaking change here, even without a clean deprecation cycle.  Others may disagree though.

**Comment by shoyer** [comment]
I agree with @mrocklin. Unlike dask.array, nobody is using dask.dataframe from other libraries (that we know of).

**Comment by mrocklin** [comment]
So quick, lets fix/break API while we still can :)

**Comment by clarkfitzg** [comment]
Ready for review.

**Comment by mrocklin** [comment]
+1 from me

**Pull request merged**
