### PR TITLE
Key names in do prepend function name

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by jcrist** [comment]
+1.

**Comment by mrocklin** [comment]
Failures are due to the recent numpy 1.10 release and are unrelated to this PR.

**Comment by mrocklin** [comment]
@jcrist I've pushed some failing commits up here.  If you are still interested in taking this over I'd be happy to jettison it.

**Comment by mrocklin** [comment]
The last one in particular isn't something that we necessarily want

**Comment by jcrist** [comment]
Superseded by #780. Closing.

**Pull request closed without merging**
