### PR TITLE
Add badge and note binder in README

### LINKED ISSUE #771: Link to dask-examples within docs
We've built some nice examples within github.com/blaze/dask-examples.  We should link to them as appropriate within the docs.

cc @cowlicks

### PR DESCRIPTION
**Pull request by cowlicks**
closes #771

### CODE REVIEW

**Comment by mrocklin** [comment]
It might be nice to link to specific binders within specific locations in the docs.  For example the array and dataframe basics notebooks might find good homes in the array and dataframe doc pages.  I suspect that both nbviewer and binder links might be useful.

See https://github.com/binder-project/binder-web/issues/9

**Comment by cowlicks** [comment]
@mrocklin hows that? Example here https://github.com/cowlicks/dask/blob/gh-771/docs/source/dataframe.rst

**Comment by mrocklin** [comment]
In principle this looks great.  To be thorough I just went through one of the links and saw that the binder examples seem to be broken.  They aren't able to handle our imports for some reason. 

A couple of options:

1.  Interface with binder folks to see what's going on [gitter chat](https://gitter.im/binder-project/binder)
2.  Roll back to nbviewer links

The hardware on binder has changed significantly since some of these notebooks were created (the machine size seems to have decreased.)  It would be wise to actually breeze through them to verify that they're still useful in a runnable state.  If not, then again rolling back to nbviewer links might be wise.

Or, more generally, the issue should probably not have read 

*Add binder links to docs*

But should have read

*Complement dask documents with the content within the dask-examples repository to generate user value.  Do everything necessary to verify that this value is real and helps beginners.*

**Comment by cowlicks** [comment]
@mrocklin I recreated the binder, and all the notebooks ran fine. I think the last person to create the binder might have done so without selecting the "requirements.txt" part. I think that anyone, can potentially recreate the binder like this whenever they want, breaking the demo notebooks for users.

**Comment by cowlicks** [comment]
Can you suggest a better way to plug the notebooks? I thought my approached seemed a bit dry.

**Comment by mrocklin** [comment]
The approach seems ok to me.  One might even go more dry with something like the following:

Example notebook: [see on nbviewer]() or [interact with binder]()

The small machine sizes still concerns me a bit.  The experience of walking through the timeseries notebook is much less pleasant without eight cores.  The do-and-profiler notebook only makes sense if there are multiple cores (otherwise the user sees no speedup when we say that there is one.)  Not sure how best to handle this.

**Comment by cowlicks** [comment]
Should we actually use nbviewer? Even though github can render the notebooks?

**Comment by cowlicks** [comment]
Maybe @freeman-lab would let us pay for better machines?

**Comment by mrocklin** [comment]
nbviewer is nice because it renders bokeh plots

**Comment by mrocklin** [comment]
We can also change the notebooks or just think about which we should make as interactive and which we keep as nbviewer links.  There is value to each.

**Comment by freeman-lab** [comment]
@cowlicks it's not that we don't want to! =) As you can imagine, anything involving money/accounts adds a new layer of complexity.

I'm fairly confident that in the short term Binder will allow containers with either 1 or "a couple" nodes, probably specified via a `binder.yml` file in the repo, maybe not exposed in the UI (credit to @mrocklin for that idea). Can't guarantee when, but we'll definitely ping you all when it happens!

And in the shorter term, I think @mrocklin 's strategy of offering different tutorials via different kinds of links makes a ton of sense (e.g. run this notebook live to explore the API, view this pre-rendered notebook for clear multi-core performance stats).

**Comment by mrocklin** [comment]
> Binder will allow containers with either 1 or "a couple" nodes

To be clear the request isn't multi-node, but single-node multi-core

**Comment by mrocklin** [comment]
Though, given the rest of your comment it seems that that was your intent anyway

**Comment by freeman-lab** [comment]
Yup, oops, I meant multi-core (just edited), clusters on the brain...

**Comment by cowlicks** [comment]
This depends on [this PR](https://github.com/blaze/dask-examples/pull/12) in the dask-examples repo.

**Comment by cowlicks** [comment]
I changed the time series notebook to be more usable on binder. And link to it and a version with profiling on nbviewer. 

The imperative docs link to the notebook on nbviewer.

Anything else?

**Comment by mrocklin** [comment]
I have to admit that I'm not tracking this very aggressively so I'm mostly trusting you here.  

Do you think we've squeezed out all of the easily accessible value out of the `dask-examples` repository?  If so then I'm +1.

**Comment by cowlicks** [comment]
Mergin'

**Pull request merged**
