### PR TITLE
Raise exception with pd.MultiIndex.

### PR DESCRIPTION
**Pull request by cowlicks**
closes gh-772

### CODE REVIEW

**Comment by mrocklin** [comment]
This also shows up in other cases, such as groupbys

```python
In [1]: import pandas as pd
df = 
In [2]: df = pd.DataFrame({'x': [1, 2, 3], 'y': [10, 20, 30], 'z': [100, 200, 300]})

In [3]: df
Out[3]: 
   x   y    z
0  1  10  100
1  2  20  200
2  3  30  300

In [4]: df.groupby(['x', 'y']).z.sum()
Out[4]: 
x  y 
1  10    100
2  20    200
3  30    300
Name: z, dtype: int64

In [5]: df.groupby(['x', 'y']).z.sum().index
Out[5]: 
MultiIndex(levels=[[1, 2, 3], [10, 20, 30]],
           labels=[[0, 1, 2], [0, 1, 2]],
           names=['x', 'y'])
```

**Comment by cowlicks** [comment]
So the exception would occur when you try to preform a groupby on more than one column?

**Comment by mrocklin** [comment]
That's one such case that I can think of.  There might be more?  I'm not
sure.

**Comment by cowlicks** [comment]
So... This actually does work sometimes. See [here](https://github.com/blaze/dask/blob/master/dask/dataframe/tests/test_dataframe.py#L341-L345).

I'm looking in to what we actually currently support and what we do not.

**Comment by cowlicks** [comment]
Okay what does not seem to work:
  * Creating a dask.dataframe from a pandas.dataframe which has a `MultiIndex`.
What seems to work:
  * Doing groupby's on on multiple columns in the dataframe. The index of the dask.dataframe that results from these is a little strange. But It seems to compute to all the right things.

@mrocklin I'm removing the exception for the case you suggested since it seems to work. I'll add a few more tests to double check it.

**Pull request merged**
