### PR TITLE
Change links from ContinuumIO to blaze org

### PR DESCRIPTION
**Pull request by mrocklin**
I grepped for `/ContinuumIO/` and replaced with `/blaze/`.  In particular I was alerted because the `travis.ci` badge was broken on the readme.

cc @chdoig @cpcloud , we may want to repeat this process across more repositories.

### CODE REVIEW

**Comment by chdoig** [comment]
@mrocklin What was wrong with PR #609?

**Comment by mrocklin** [comment]
Oh crap.  I assumed that that had already been merged.

**Comment by mrocklin** [comment]
Yup, now I feel pretty silly.  My apologies.

**Comment by chdoig** [comment]
No worries. I submitted a PR to all the repos I moved. @cpcloud merged them for odo, blaze and datashape. So, we should be good on those.

**Pull request merged**
