### PR TITLE
Add function to make random time series

### PR DESCRIPTION
**Pull request by mrocklin**
This is primarily for experimentation and demonstration

Example
-------

```python
>>> import dask.dataframe as dd
>>> df = dd.demo.make_timeseries('2000', '2010',
...                              {'value': float, 'name': str, 'id': int},
...                              freq='2H', partition_freq='1D', seed=1)
>>> df.head()
                       id    name     value
2000-01-01 00:00:00   971   Edith -0.053963
2000-01-01 02:00:00   937   Kevin -0.625998
2000-01-01 04:00:00   965  Xavier -0.922559
2000-01-01 06:00:00  1011   Sarah  0.866421
2000-01-01 08:00:00  1005   Zelda -0.319609
```

### CODE REVIEW

**Comment by mrocklin** [comment]
Merging soon if no comments

**Comment by TomAugspurger** [comment]
FYI, there's a a bunch of these types of dataframe generating functions in https://github.com/pydata/pandas/blob/master/pandas/util/testing.py if it's easier to wrap those.

**Comment by mrocklin** [comment]
I've used those in the past.  They're handy and largely why I wanted to build this function.  The time series stuff would be easy to wrap *if* they allowed for different start times.  It seems like they always start at 2000 though.  In any event I'm pretty happy with the control this function provides.

**Comment by TomAugspurger** [comment]
:+1:

**Pull request merged**
