### PR TITLE
Fix shell injection in dask.dot.dot_graph

### PR DESCRIPTION
**Pull request by ssanderson**
Fixes https://github.com/blaze/dask/issues/670

### CODE REVIEW

**Comment by ssanderson** [comment]
Not sure what's up with the travis failure.  Looks like the 3.3 and 2.6 builds are on older versions of toolz?

**Comment by mrocklin** [comment]
Oh, yeah, Anaconda recently dropped automatic support for 2.6 and 3.3.  I see two options. 

Switch to pip within .travis.ci

Replace the line

    dot, pdf, png = map(add(filename), ('.dot', '.pdf', '.png'))
    with 
    dot, pdf, png = [filename + ext for ext in ['.dot', '.pdf', '.png']]

My personal preference is on the latter.  This is also probably more friendly to the non-functional programmers out there.

In general I think that this approach is a good one, and I appreciate people thinking about security.  

An alternative approach is to avoid subprocess altogether and depend on the `graphviz` python library (which we switched to recently.) which apparently has a direct function for calling down to `dot`.

    g.pipe(format='png')
    g.pipe(format='pdf')

**Comment by ssanderson** [comment]
@mrocklin updated to use the simpler comprehension.  It's still a bit surprising to me that travis runs with package versions that are different from what you'd get with a clean `pip install dask[complete]`, but I'm not sure what the right fix is on that front.  At any rate that change seems like it's outside the scope of what's being fixed here.

Using `pipe` also seems like a reasonable option (and it looks like that's what's already being used if the user explicitly passes `filename=None`.

**Comment by ssanderson** [comment]
I mocked out what I think a reasonable implementation would look like using `pipe` everywhere.  One thing that seemed worth doing was making it possible for the user to supply their desired format, rather than just always writing a pdf and a png.  In particular, the SVGs produced by dot are often a bit nicer to look at than the PNGs, in my opinion.

This is what I have working locally:

```
def _get_display_cls(format):
    dummy = lambda *args, **kwargs: None
    if format == 'pdf':
        # IPython can't display PDF.
        return dummy

    try:
        import IPython.display as display
    except ImportError:
        # Can't return a display object if no IPython.
        return dummy

    if format == 'svg':
        return display.SVG
    else:
        # Partially apply `format` so that this and `SVG` supply a uniform
        # interface to the caller.
        return partial(display.Image, format=format)


def dot_graph(dsk, filename='mydask', format='png', **kwargs):
    g = to_graphviz(dsk, **kwargs)
    data = g.pipe(format=format)
    display_cls = _get_display_cls(format)

    if filename is None:
        return display_cls(data=data)

    full_filename = '.'.join([filename, format])
    with open(full_filename, 'wb') as f:
        f.write(data)

    return _get_display_cls(format)(filename=full_filename)
```

If you're interested in supporting user-control over output format, I can open up a separate PR with these changes.

**Comment by mrocklin** [comment]
That looks much cleaner than what's there now.  This would be appreciated.

**Comment by ssanderson** [comment]
Opened #674 on top of this branch.

**Pull request merged**
