### PR TITLE
Series to_csv

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by lakshmanok** [comment]
Thanks!   This now works:

```
estimates = alldata.groupby('Id').apply(myfunc, columns=['Id','Expected'])
estimates.to_csv(outfile, header=True)
```

but there may be a bug.  The header of the output csv has "Id" as the name of the first column but "0" as the name of the second.

**Comment by mrocklin** [comment]
Hrm, is `estimates` supposed to be a `DataFrame` with two columns or a `Series` with one column (expected).

You might want to try the following:

```python
estimates = alldata.groupby('Id').apply(myfunc, columns='Expected')
estimates.to_csv(outfile, header=True)
```

**Comment by lakshmanok** [comment]
Same result.  The column name is still zero after your suggested change.

**Comment by mrocklin** [comment]
Hrm, can you share a tiny example that would reproduce this error?

**Comment by lakshmanok** [comment]
```
#!/usr/bin/env python
#
import dask.dataframe as dd
import pandas as pd

outfile = '/tmp/out.csv'
df = pd.DataFrame({'Id': [1,1,2,2,2],
                   'Count': [43.,42.,43.,21.,45.]})
alldata = dd.from_pandas(df, 2)

def myfunc(gp):
    return gp['Count'].sum()

# this writes out the file, but there is a bug in dask
# where the column name is '0': https://github.com/blaze/dask/pull/621
estimates = alldata.groupby('Id').apply(myfunc, columns='Expected')
estimates.to_csv(outfile, header=True)

# print out header
infile = open(outfile, 'r')
print infile.readline()

```

**Pull request merged**
